---
title: "Final Presentation"
author: "Jeremy Forbes"
date: "19/09/2018"
output: html_document
---

Work things into 25 slides


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Motivation

- Changing Australian demographic: stats on particular variables

- Maps of Australia with electorates shaded by their TPP vote

## Research question

How do socio-demographics relate to the two-party preferred vote, and how has this changed over time?

## Literature review

- Australian election studies

- Other common voting methods

- Ecological studies

- Akaike weights

## What is involved in answering this question

- Collecting and cleaning Census and election data

- Creating a method to impute data due to census and election mismatch

- Dimension reduction and variable selection

- Linear regression for each election (can't use a longitudinal model)

## Data gathering and wrangling

- Raw data obtained in messy .csv format (inconsistent across Census questions)

- Followed Stimson's lead in defining some useful variables

- Clean data frames in R

## Imputation

- Existing methods based on centroids were problematic because of weird electorate shapes

- New algorithm which uses GIS data to define polygons, and impute based on overlapping regions

## Imputation: Example

- Describe how imputation works with a single electorate

## Dimension Reduction

- PCA and factor creation

## Variable selection

- Brief explanation of Information-theoretic approach with AIC and model set

- Sum of Akaike weights as a measure of variable importance

- We run all possible 5 variable models for each election, which functions as our model set

## The most important variables

- List the included variables

- Notable omissions

- What does this mean in terms of omitted variable bias

## Interactions

- Criteria for selection

- Inclusions

## Resultant model

- Written in maths

- Perhaps a visual showing how coefficients (fixed effects and interactions) vary

## Fixed effects

- Discuss the influential ones

- Discuss the changing ones

## Interactions

- Changing ones

## Diagnostics

- QQ plots: Residuals are normal

- No sign of significant non-linearities in the predictors

- No sign of significant relationship between excluded variables and residuals in any year

- High influence points: Kalgoorlie and Sydney - why this is

## Discussion

- What can we say about which socio-demographics matter?

- What are the broader implications of this?

- Spatial correlation in the residuals

## Next

- Fit spatial error models to allow for correlation in the residuals

- Have all data available on GitHub in the eechidna package

